"""Redo migrations

Revision ID: fe2f2952544b
Revises: a720887b87e8
Create Date: 2025-02-16 19:25:31.210448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2f2952544b'
down_revision: Union[str, None] = 'a720887b87e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('editing_sessions_user_id_fkey', 'editing_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'editing_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('editing_sessions', 'is_active')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.add_column('editing_sessions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'editing_sessions', type_='foreignkey')
    op.create_foreign_key('editing_sessions_user_id_fkey', 'editing_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
